import type { PrismaClient } from '@prisma/client';
import type { ITripRepository } from '../application/ports/repositories/trip.repository.js';
import type { IExpenseRepository } from '../application/ports/repositories/expense.repository.js';
import type { IMemberRepository } from '../application/ports/repositories/member.repository.js';
import type { IInvitationRepository } from '../application/ports/repositories/invitation.repository.js';
import type { IUserRepository } from '../application/ports/repositories/user.repository.js';
import type { ITripMemberRepository } from '../application/ports/repositories/trip-member.repository.js';
import type { IAuthService } from '../application/ports/services/auth.service.js';
import type { IEmailService } from '../application/ports/services/email.service.js';
import type { IRateLimitService } from '../application/ports/services/rate-limit.service.js';
import type { ITripAccessService } from '../application/ports/services/trip-access.service.js';
import type { IEmailBloomFilterService } from '../application/ports/services/email-bloom-filter.service.js';
import type { ITransactionManager } from '../application/ports/transaction-manager.js';
import type { GetTripsUseCase } from '../application/use-cases/trips/get-trips.use-case.js';
import type { CreateTripUseCase } from '../application/use-cases/trips/create-trip.use-case.js';
import type { GetTripUseCase } from '../application/use-cases/trips/get-trip.use-case.js';
import type { UpdateTripUseCase } from '../application/use-cases/trips/update-trip.use-case.js';
import type { DeleteTripUseCase } from '../application/use-cases/trips/delete-trip.use-case.js';
import type { InviteMemberUseCase } from '../application/use-cases/trips/invite-member.use-case.js';
import type { JoinTripUseCase } from '../application/use-cases/trips/join-trip.use-case.js';
import type { RemoveCollaboratorUseCase } from '../application/use-cases/trips/remove-collaborator.use-case.js';
import type { CreateExpenseUseCase } from '../application/use-cases/expenses/create-expense.use-case.js';
import type { UpdateExpenseUseCase } from '../application/use-cases/expenses/update-expense.use-case.js';
import type { DeleteExpenseUseCase } from '../application/use-cases/expenses/delete-expense.use-case.js';
import type { CreateMemberUseCase } from '../application/use-cases/members/create-member.use-case.js';
import type { UpdateMemberUseCase } from '../application/use-cases/members/update-member.use-case.js';
import type { DeleteMemberUseCase } from '../application/use-cases/members/delete-member.use-case.js';
import type { GetInvitationsUseCase } from '../application/use-cases/invitations/get-invitations.use-case.js';
import type { AcceptInvitationUseCase } from '../application/use-cases/invitations/accept-invitation.use-case.js';
import type { UpdateProfileUseCase } from '../application/use-cases/users/update-profile.use-case.js';
import type { CheckEmailUseCase } from '../application/use-cases/check-email/check-email.use-case.js';

export type AppRegistry = {
  PRISMA_CLIENT: PrismaClient;
  TRIP_REPOSITORY: ITripRepository;
  EXPENSE_REPOSITORY: IExpenseRepository;
  MEMBER_REPOSITORY: IMemberRepository;
  INVITATION_REPOSITORY: IInvitationRepository;
  USER_REPOSITORY: IUserRepository;
  TRIP_MEMBER_REPOSITORY: ITripMemberRepository;
  AUTH_SERVICE: IAuthService;
  EMAIL_SERVICE: IEmailService;
  AUTH_RATE_LIMITER: IRateLimitService;
  API_RATE_LIMITER: IRateLimitService;
  EMAIL_RATE_LIMITER: IRateLimitService;
  TRIP_ACCESS_SERVICE: ITripAccessService;
  EMAIL_BLOOM_FILTER_SERVICE: IEmailBloomFilterService;
  TRANSACTION_MANAGER: ITransactionManager;
  GET_TRIPS_USE_CASE: GetTripsUseCase;
  CREATE_TRIP_USE_CASE: CreateTripUseCase;
  GET_TRIP_USE_CASE: GetTripUseCase;
  UPDATE_TRIP_USE_CASE: UpdateTripUseCase;
  DELETE_TRIP_USE_CASE: DeleteTripUseCase;
  INVITE_MEMBER_USE_CASE: InviteMemberUseCase;
  JOIN_TRIP_USE_CASE: JoinTripUseCase;
  REMOVE_COLLABORATOR_USE_CASE: RemoveCollaboratorUseCase;
  CREATE_EXPENSE_USE_CASE: CreateExpenseUseCase;
  UPDATE_EXPENSE_USE_CASE: UpdateExpenseUseCase;
  DELETE_EXPENSE_USE_CASE: DeleteExpenseUseCase;
  CREATE_MEMBER_USE_CASE: CreateMemberUseCase;
  UPDATE_MEMBER_USE_CASE: UpdateMemberUseCase;
  DELETE_MEMBER_USE_CASE: DeleteMemberUseCase;
  GET_INVITATIONS_USE_CASE: GetInvitationsUseCase;
  ACCEPT_INVITATION_USE_CASE: AcceptInvitationUseCase;
  UPDATE_PROFILE_USE_CASE: UpdateProfileUseCase;
  CHECK_EMAIL_USE_CASE: CheckEmailUseCase;
};
